### ISSUE TITLE
Signature Request Payload Collision

### ISSUE THREAD

**Issue by think-in-universe** [near/mpc#548]
### Description

The MPC contract now uses payload as the key for chain signature request and response: https://github.com/near/mpc-recovery/blob/e1cbbd0d03500844008bdf48d981356263c3b7ec/contract/src/lib.rs#L370-L372

But it's possible that payloads from different users can be the same and leads to key collision (if nonces are the same). The latter request cannot be sent until the former one with the same payload is fulfilled.

This can be reproduced by sending the same amount of ETH to the same addresses from two new derived accounts, with the demo component by Matt: https://test.near.social/md1.testnet/widget/chainsig-sign-eth-tx

**Comment by ppca** [comment]
This won't be a problem any further because we now use
```
pub struct SignatureRequest {
    pub epsilon: SerializableScalar,
    pub payload_hash: [u8; 32],
}
```
as the key chain signature request and response, where epsilon is calculated based on path and predecessor of the request. So even if the two requests have the same payload, they won't have a clash unless predecessor and path are also the same.

**Comment by volovyks** [comment]
@ppca are we handling the case where the same user calls the contract with the same payload? Are we rejecting such a call in new Y/R design?

**Comment by ppca** [comment]
Yes it will be rejected still until it's completed or timed out.
