### ISSUE TITLE
Timeout error rate is high

### ISSUE THREAD

**Issue by volovyks** [near/mpc#762]
@gagdiez  reported 90% error rate, we should find the reason. I do not think it is the capacity of our system.

**Comment by gagdiez** [comment]
This is my general experience: 

<img width="1276" alt="Screenshot 2024-07-30 at 14 31 04" src="https://github.com/user-attachments/assets/25f6f48f-9637-40a1-9a41-4b928002d9d1">


I make a call, the `wallet` or the contract time out while waiting, I call again the contract, now the contract fails because I already asked for the signature, I wait and ask the signature again, the time out happens again, I try again and either the contract or wallet timeout, I try again and the circle repeats

Sometimes it takes me 15min to get a valid signature, out of clicking every 3 to 4 minutes on the retry button

**Comment by gagdiez** [comment]
This would be solved automatically by caching the answer as this example does: 

https://github.com/gagdiez/yield-resume/blob/1a0532c550e0ebc19eed05db0c650e43925c8629/contracts/retry-on-error/src/lib.rs#L48-L60

**Comment by volovyks** [comment]
We have a high error rate because we stoped generation triples on our dev env. Other concerns are valid.
