### ISSUE TITLE
Make Grafana Public

### ISSUE THREAD

**Issue by volovyks** [near/mpc#891]
### Description

```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc/issues/930
```

**Comment by kmaus-near** [comment]
Update on public dashboards:

I don't think this will fit our use case due to [live data not being supported](https://grafana.com/docs/grafana-cloud/visualizations/dashboards/share-dashboards-panels/shared-dashboards/#limitations). As an alternative, perhaps we can publish terraform code to provision our current dashboards and alerts for our partners. This may take a bit of effort to complete, and probably won't be a plug and play solution for them, but it can give them an idea of what we are monitoring.

**Comment by auto-mausx** [comment]
Our previous discussion was to make our grafana repo public for partners to use as an example and deploy on their own infrastructure, I think this is a great idea.

I have removed all of our URLs for our grafana instance and will work on a README on how to deploy into an environment (High level). 

One issue is the commit history will have our old URLs, so I will use a tool to remove those from commit history. It will require anyone who has cloned this repo to delete their local copy and re-clone the redacted version. I think @volovyks may be the only one who has cloned the repo, I will update when the repo commit history has been redacted.

**Comment by volovyks** [comment]
Sure, np.

**Comment by auto-mausx** [comment]
Here's our Public grafana repo, should be sanitized of URLs so we can avoid any fishy stuff with that. Let me know if the README makes sense.

https://github.com/sig-net/sig-grafana

**Comment by volovyks** [comment]
Looks good. Let's share it with our partners and get feedback. We should gradually push the idea that they all need alerts and dashboards (this one or the one of their choice).
