### ISSUE TITLE
Investigate why recovery from big_r doesn't work.

### ISSUE THREAD

**Issue by robin-near** [near/mpc#98]

**Comment by SimonRastikian** [comment]
Cait-Sith optionally normalizes s following BIP 0062 to deal with potential problems:
normalizing s means that before the signing algorithm outputs the signature it checks whether s is in the lower half or the upper half of [0, n-1]
if it is in the lower half, it keeps it the same. Otherwise it overwrites the value doing  n-s. Any value s output by the signature is thus between [0, n/2].
Because of this, recovering the id using recovery_from_big_r  is not possible. In fact, normalizing implies blurring the boundaries between s and -s. This sign is essential to recover the id:
recovering public key depends on both: the sign of R and the sign of s. But because the information from the latter is missing, it is impossible to recover the id without brute forcing.
I tested a modification of cait-sith where I prevented this normalization from happening before outputting the signature. Then I applied my function and allowed the verification not to check for normalizations.
The result is that contract.rs passed!
The  opt solution is using the brute forcing technique instead of getting rid of the normalization in cait-sith ( the latter reduces the security from strong unforgeability to existential unforgeability/weak unforgeability)
